"""empty message

Revision ID: 1b896c1988d9
Revises: d468313ef1ed
Create Date: 2016-02-23 11:38:40.462509

"""

# revision identifiers, used by Alembic.
revision = '1b896c1988d9'
down_revision = 'd468313ef1ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('act_date', sa.DateTime(), nullable=True))
    op.drop_column('session', 'create_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('create_date', mysql.DATETIME(), nullable=True))
    op.drop_column('session', 'act_date')
    ### end Alembic commands ###
