"""empty message

Revision ID: 3be461541e86
Revises: 87e048dd8848
Create Date: 2016-02-28 20:32:23.446702

"""

# revision identifiers, used by Alembic.
revision = '3be461541e86'
down_revision = '87e048dd8848'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=120), nullable=True))
    op.drop_index('username', table_name='user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user', ['username'], unique=True)
    op.drop_column('user', 'password')
    ### end Alembic commands ###
