"""empty message

Revision ID: 87e048dd8848
Revises: e2623e46deed
Create Date: 2016-02-28 22:08:05.001720

"""

# revision identifiers, used by Alembic.
revision = '87e048dd8848'
down_revision = 'e2623e46deed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vkuid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vkuid')
    ### end Alembic commands ###
