"""empty message

Revision ID: 9107c65f103e
Revises: 51635ba5d0d9
Create Date: 2016-02-28 20:44:13.444604

"""

# revision identifiers, used by Alembic.
revision = '9107c65f103e'
down_revision = '51635ba5d0d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=92), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    ### end Alembic commands ###
