"""empty message

Revision ID: a0935458ada1
Revises: 0ca7bedd76a8
Create Date: 2016-02-28 21:24:33.556218

"""

# revision identifiers, used by Alembic.
revision = 'a0935458ada1'
down_revision = '0ca7bedd76a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    ### end Alembic commands ###
