"""empty message

Revision ID: adaab21d8a20
Revises: a0935458ada1
Create Date: 2016-03-07 13:24:14.361756

"""

# revision identifiers, used by Alembic.
revision = 'adaab21d8a20'
down_revision = 'a0935458ada1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gcmid', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gcmid')
    ### end Alembic commands ###
