"""empty message

Revision ID: e2623e46deed
Revises: f7e070c9abaa
Create Date: 2016-02-27 17:29:22.383611

"""

# revision identifiers, used by Alembic.
revision = 'e2623e46deed'
down_revision = 'f7e070c9abaa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('closed', sa.DateTime(), nullable=True))
    op.add_column('queue', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('queue', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queue', 'description')
    op.drop_column('queue', 'created')
    op.drop_column('queue', 'closed')
    ### end Alembic commands ###
