"""empty message

Revision ID: f7e070c9abaa
Revises: 1b896c1988d9
Create Date: 2016-02-25 23:43:44.425041

"""

# revision identifiers, used by Alembic.
revision = 'f7e070c9abaa'
down_revision = '1b896c1988d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('current', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue')
    ### end Alembic commands ###
